apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcamp-server
  template:
    metadata:
      labels:
        app: bootcamp-server
    spec:
      containers:
      - name: bootcamp-server
        image: registry.sensetime.com/diamond/zhangxiaohu/bootcamp/server:v0.1.0
        imagePullPolicy: Always
        args: ["--binding-address","0.0.0.0","--port","9000","--data-path","/tmp/data"]
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /tmp/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: operator-tool-server
